# Generated by Django 3.0.5 on 2020-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porjectmanage', '0002_auto_20200509_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(max_length=302, null=True),
        ),
    ]
