# Generated by Django 3.0.5 on 2020-05-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porjectmanage', '0005_auto_20200510_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('00_low', 'Low'), ('10_normal', 'Normal'), ('20_high', 'High'), ('30_critical', 'Critical'), ('40_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='state'),
        ),
    ]
