# Generated by Django 3.0.5 on 2020-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalation', '0002_postinstalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinstalation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='preinstalation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
