# Generated by Django 3.0.5 on 2020-05-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dismantle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdismantle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='predismantle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
